name: Build and publish Docker
on: 
  push:
    branches: 
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: arjanz/substrate-client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: $(echo ${GITHUB_REF#refs/heads/})-latest
